DROP TABLE IF EXISTS bus;
DROP TABLE IF EXISTS conductor;
DROP TABLE IF EXISTS driver;
DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
userid INTEGER UNSIGNED UNIQUE PRIMARY KEY AUTO_INCREMENT,
password TEXT NOT NULL,
name varchar(50));
ALTER TABLE admin AUTO_INCREMENT=10001;

CREATE TABLE conductor (
userid INTEGER UNSIGNED UNIQUE PRIMARY KEY AUTO_INCREMENT,
password TEXT NOT NULL,
name varchar(50));
ALTER TABLE conductor AUTO_INCREMENT=20001;

CREATE TABLE driver (
userid INTEGER UNSIGNED UNIQUE PRIMARY KEY AUTO_INCREMENT,
name varchar(50));
ALTER TABLE driver AUTO_INCREMENT=60001;

CREATE TABLE bus (
registration varchar(15) UNIQUE PRIMARY KEY,
conductor_id INTEGER UNSIGNED UNIQUE NOT NULL,
driver_id INTEGER UNSIGNED UNIQUE DEFAULT NULL,
route varchar(15) NOT NULL,
type varchar(50),
stop_index INTEGER,
stop_time TIME,
seat_available BOOLEAN DEFAULT 1,
FOREIGN KEY (driver_id) REFERENCES driver (userid),
FOREIGN KEY (conductor_id) REFERENCES conductor (userid));